name: Deploy VectorWing to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'vectorwing-next/**'
      - '.github/workflows/deploy-pages.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Next.js static export
        working-directory: vectorwing-next
        env:
          # For GitHub Project Pages (https://<owner>.github.io/<repo>/) the basePath must be "/<repo>"
          BASE_PATH: /${{ github.event.repository.name }}
        run: |
          npm ci
          npm run export

      - name: Upload prototype as Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: vectorwing-next/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4


